// <auto-generated />
using System;
using EmployeeManagmentAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagmentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmploymentManagement.Model.Department", b =>
                {
                    b.Property<int>("DepartemntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartemntName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartemntID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartemntID = 1,
                            DepartemntName = "Dep1"
                        },
                        new
                        {
                            DepartemntID = 2,
                            DepartemntName = "IT"
                        },
                        new
                        {
                            DepartemntID = 3,
                            DepartemntName = "Security"
                        },
                        new
                        {
                            DepartemntID = 4,
                            DepartemntName = "Sales"
                        });
                });

            modelBuilder.Entity("EmploymentManagement.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "first@gmail.com",
                            FirstName = "firstname1",
                            Gender = 0,
                            LastName = "lastname1",
                            PhotoPath = "images/john.jpg"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "first@gmail.com",
                            FirstName = "two",
                            Gender = 0,
                            LastName = "lastname1",
                            PhotoPath = "images/two.jpg"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "first@gmail.com",
                            FirstName = "third",
                            Gender = 0,
                            LastName = "lastname1",
                            PhotoPath = "images/third.jpg"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "first@gmail.com",
                            FirstName = "fourth",
                            Gender = 0,
                            LastName = "lastname1",
                            PhotoPath = "images/fourth.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
